# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_later', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redditlink',
            name='url',
        ),
    ]
