# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RedditLink',
        ),
    ]
